### ISSUE TITLE
copy fails to copy when destination is directory

### ISSUE THREAD

**Issue by borismod** [jmcgeheeiv/pyfakefs#102]
shutil.copy fails to copy with the following exception

> Error
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 329, in run
  File "C:\work\GitHub\shellfoundry\tests\test_package_builder.py", line 32, in test_copy
  File "C:\Python27\lib\shutil.py", line 119, in copy
  File "C:\Python27\lib\shutil.py", line 83, in copyfile
  File "C:\Python27\lib\site-packages\pyfakefs\fake_filesystem.py", line 1896, in __call__
  File "C:\Python27\lib\site-packages\pyfakefs\fake_filesystem.py", line 1904, in _call_ver2
  File "C:\Python27\lib\site-packages\pyfakefs\fake_filesystem.py", line 1971, in Call
IOError: [Errno 21] Fake file object: is a directory: u'C:\\destination'

According to its documentation, if the destination is directory it should copy the file to destination.

> **shutil.copy(src, dst)**
Copy the file src to the file or directory dst. If dst is a directory, a file with the same basename as src is created (or overwritten) in the directory specified. Permission bits are copied. src and dst are path names given as strings.

[10.10. shutil — High-level file operations](https://docs.python.org/2/library/shutil.html)

Unit test to reproduce the issue:

```Python
import os
import unittest
from shutil import copy
from pyfakefs import fake_filesystem_unittest


class TestPackageBuilder(fake_filesystem_unittest.TestCase):
    def setUp(self):
        self.setUpPyfakefs()

    def test_copy(self):
        self.fs.CreateFile(u'C:\\source\\file.txt', contents='')
        os.makedirs(u'C:\destination')
        copy(u'C:\\source\\file.txt', u'C:\destination')

        self.assertFileExists(u'C:\destination\\file.txt')

    def assertFileExists(self, file_path):
        self.assertTrue(os.path.exists(file_path))
```

**Comment by mrbean-bremen** [comment]
The problem is "import copy from shutil". This way, after pyfakefs replaces shutil with its own implementation, copy is still used from the system lib (as can be seen in the callstack).
Using:
```
import shuti
...
shutil.copy(...)
```
instead should fix the problem.

**Comment by borismod** [comment]
@mrbean-bremen thank you for your reply. It fixes the issue.
