### ISSUE TITLE
Wrong exceptions raised on failing operations

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#209]
This code:

import pyfakefs.fake_filesystem

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)
component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/alpha"
path0 = path1 + "/alpha"
os0.symlink(path0,path1) 
os0.makedirs(path0) 

Produces this failure:

Traceback (most recent call last):
  File "bug1.py", line 13, in <module>
    os0.makedirs(path0) 
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 3007, in makedirs
    self.filesystem.MakeDirectories(dir_name, mode, exist_ok)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 1801, in MakeDirectories
    current_dir = current_dir.contents[component]
TypeError: string indices must be integers, not str

To match Python os module behavior, it should produce:

Traceback (most recent call last):
  File "bug1os.py", line 10, in <module>
    os0.makedirs(path0) 
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 62] Too many levels of symbolic links: '/Volumes/ramdisk/test/alpha/alpha'

A very similar problem, not involving symbolic links, is to replace

os0.symlink(path0,path1)

with

os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)

that gives the failure:

Traceback (most recent call last):
  File "bug2.py", line 14, in <module>
    os0.makedirs(path0) 
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 3007, in makedirs
    self.filesystem.MakeDirectories(dir_name, mode, exist_ok)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 1803, in MakeDirectories
    self.CreateDirectory(dir_name, mode & ~self.umask)
  File "/Users/alex/tstl/examples/pyfakefs/pyfakefs/fake_filesystem.py", line 1571, in CreateDirectory
    current_dir.AddEntry(new_dir)
AttributeError: 'FakeFile' object has no attribute 'AddEntry'

when to match os it should be:

Traceback (most recent call last):
  File "bug2os.py", line 9, in <module>
    os0.makedirs(path0) 
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/Volumes/ramdisk/test/alpha/alpha'

These were discovered using TSTL, a test generation tool (https://github.com/agroce/tstl).

**Comment by mrbean-bremen** [comment]
Shall be fixed, please verify.

**Comment by mrbean-bremen** [comment]
@agroce - I'm going to close the fixed issues now, you can always reopen them if you find a related problem. Looks like there will be a lot of new issues soon...
