### ISSUE TITLE
Rename priorities of checks

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#233]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "beta" 
os0.symlink(path0,path1) 
path0 = path1 + "/" + component0 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.rename(path0,path0) 

On pyfakefs, fails with 

Traceback (most recent call last):
  File "bug20.py", line 24, in <module>
    os0.rename(path0,path0) 
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 3526, in rename
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 1844, in RenameObject
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 1723, in GetObject
  File "build/bdist.macosx-10.6-intel/egg/pyfakefs/fake_filesystem.py", line 1697, in GetObjectFromNormalizedPath
IOError: [Errno 20] Not a directory in fake filesystem: '/Volumes/ramdisk/test/alpha/beta'

os just silently does nothing, since that is the behavior for rename(X,X).  Easy to fix, I suppose, and not particularly important, but here it is.

**Comment by mrbean-bremen** [comment]
Actually another symlink issue.

**Comment by agroce** [comment]
Rename with no directory arguments, in the absence of symlinks, seems to be ok now.  I'll turn on directories -- is it expected to match os with those in?

**Comment by mrbean-bremen** [comment]
Well, lets try and see... it is expected, but there's that difference between theory and practice.
