### ISSUE TITLE
Case-sensitivity issue causes KeyError failure in rename

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#308]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "Beta" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "beta" 
path1 = "/Volumes/ramdisk/test" 
path1 += "/" + component0 
os0.mkdir(path0) 
os0.rename(path1,path0) 

Just succeeds in os, but in pyfakefs:

Traceback (most recent call last):
  File "bug60.py", line 22, in <module>
    os0.rename(path1,path0) 
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 3619, in rename
    self.filesystem.RenameObject(old_file_path, new_file_path)
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 2029, in RenameObject
    object_to_rename = old_dir_object.GetEntry(old_name)
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 720, in GetEntry
    return self.contents[pathname_name]
KeyError: 'beta'

**Comment by mrbean-bremen** [comment]
Similar problem as the other one - coud have seen this. At least it is easy to fix!

**Comment by mrbean-bremen** [comment]
If not doing a lot of typos of course...
