### ISSUE TITLE
Another symlink / case sensitivity issue

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#310]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "alpha" 
path0 = "/Volumes/ramdisk/test" 
path0 += "/" + component0 
component0 = "Alpha" 
path1 = "/Volumes/ramdisk/test" 
os0.mkdir(path0) 
path0 += "/" + component0 
os0.symlink(path1,path0) 
path0 += "/" + component0 
stat0 = os0.stat(path0) 

Works fine in os, but pyfakefs gives:

Traceback (most recent call last):
  File "bug60.py", line 26, in <module>
    stat0 = os0.stat(path0) 
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 3600, in stat
    return self.filesystem.GetStat(entry_path, follow_symlinks)
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 1053, in GetStat
    io_error.strerror, entry_path)
  File "/Users/alex/tstl/examples/mutateProbe/pyfakefs/pyfakefs/fake_filesystem.py", line 159, in raise_os_error
    raise OSError(errno, message, filename)
OSError: [Errno 2] No such file or directory in fake filesystem: '/Volumes/ramdisk/test/alpha/Alpha/Alpha'

**Comment by mrbean-bremen** [comment]
I love symlinks :/
