### ISSUE TITLE
Incorrect Python 3 file name handling.

### ISSUE THREAD

**Issue by mooman219** [jmcgeheeiv/pyfakefs#325]
I have a gzip test that's testing binary file name support.
```python
def test_bytes_filename(self):
    str_filename = '@test'
    try:
        bytes_filename = str_filename.encode("ascii")
    except UnicodeEncodeError:
        self.skipTest("Temporary file name needs to be ASCII")
    with gzip.GzipFile(bytes_filename, "wb") as f:
        f.write(data1 * 50)
    with gzip.GzipFile(bytes_filename, "rb") as f:
        self.assertEqual(f.read(), data1 * 50)
    # Sanity check that we are actually operating on the right file.
    with gzip.GzipFile(str_filename, "rb") as f:
        self.assertEqual(f.read(), data1 * 50)
```
The setup for the test looks like:
```python
class BaseTest(unittest.TestCase):
    patcher = None

    def setUp(self):
        self.patcher = Patcher()
        self.patcher.setUp()

    def tearDown(self):
        self.patcher.tearDown()
```
This test works on a real file system for python 2 and 3. It works on pyfakefs in python 2, but not in python 3. The resulting error in python 3 looks like:
```
ERROR: test_bytes_filename (apitools.base.py.gzip_test.TestGzip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/jcumbo/Documents/Repo/gsutil/third_party/apitools/apitools/base/py/gzip_test.py", line 416, in test_bytes_filename
    with gzip.GzipFile(bytes_filename, "wb") as f:
  File "/usr/local/google/home/jcumbo/Documents/Repo/gsutil/third_party/apitools/apitools/base/py/gzip.py", line 162, in __init__
    fileobj = self.myfileobj = io.open(filename, mode or 'rb')
  File "/usr/local/google/home/jcumbo/Python/py3/lib/python3.4/site-packages/pyfakefs/fake_filesystem.py", line 3551, in open
    return fake_open(file_path, mode, buffering, encoding, errors, newline, closefd, opener)
  File "/usr/local/google/home/jcumbo/Python/py3/lib/python3.4/site-packages/pyfakefs/fake_filesystem.py", line 3840, in __call__
    return self.Call(*args, **kwargs)
  File "/usr/local/google/home/jcumbo/Python/py3/lib/python3.4/site-packages/pyfakefs/fake_filesystem.py", line 3896, in Call
    real_path = self.filesystem.ResolvePath(file_path)
  File "/usr/local/google/home/jcumbo/Python/py3/lib/python3.4/site-packages/pyfakefs/fake_filesystem.py", line 1447, in ResolvePath
    file_path = self.NormalizePath(self.NormalizeCase(file_path))
  File "/usr/local/google/home/jcumbo/Python/py3/lib/python3.4/site-packages/pyfakefs/fake_filesystem.py", line 1100, in NormalizePath
    (self.cwd != root_name and self.cwd or empty, path))
TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by mrbean-bremen** [comment]
Thanks for the catch! I had a quick look, and there may be a few places where byte file names are not handled correctly - this never came up until now. I will have a closer look at this in the evening, if I find the time.

**Comment by mrbean-bremen** [comment]
Note that this may not be a complete fix - we are just converting byte filenames to strings while resolving the path. If this cannot be done using the local encoding, this will fail. I think we can live with that for now, as cases of byte-string file names that cannot be converted to strings are quite exotic.
