### ISSUE TITLE
Pickled FakeFilesystem causes RecursionError when unpickling

### ISSUE THREAD

**Issue by ttsalo** [jmcgeheeiv/pyfakefs#445]
When unpickling a pickled FakeFilesystem object, the __getattr__ method of FakeFile loops forever.

```
import pickle
from pyfakefs import fake_filesystem
filesystem = fake_filesystem.FakeFilesystem()
filesystem.open_files = []
p = pickle.dumps(filesystem)
pickle.loads(p)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 477, in __getattr__
    return getattr(self.stat_result, item)
  File ".local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 477, in __getattr__
    return getattr(self.stat_result, item)
  File ".local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 477, in __getattr__
    return getattr(self.stat_result, item)
  [Previous line repeated 323 more times]
RecursionError: maximum recursion depth exceeded
```

The fix is fairly simple, use the same conditional as __setattr__ already does :
```
--- fake_filesystem.py.orig	2018-10-24 14:05:28.497666345 +0300
+++ fake_filesystem.py	2018-10-15 14:32:20.872485946 +0300
@@ -471,13 +471,15 @@
           st_ctime: The desired creation time.
         """
         self.st_ctime = st_ctime
 
     def __getattr__(self, item):
         """Forward some properties to stat_result."""
-        return getattr(self.stat_result, item)
+        if item in self.stat_types:
+            return getattr(self.stat_result, item)
+        return super(FakeFile, self).__getattr__(item)
 
     def __setattr__(self, key, value):
         """Forward some properties to stat_result."""
         if key in self.stat_types:
             return setattr(self.stat_result, key, value)
         return super(FakeFile, self).__setattr__(key, value)
```
I can make a pull request if needed

**Comment by mrbean-bremen** [comment]
Thanks - could have sworn I already fixed that some time ago... ah well.
I can fix this in the evening, or you can make a PR - as you said, the fix is trivial.

**Comment by mrbean-bremen** [comment]
Thanks again for the report - you seem to use pyfakefs in ways no one tried before...
