### ISSUE TITLE
Regression: modules_to_patch fails if fake module has no dir() method

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#450]
The following code, taken from the documentation:
```python
class DummyLocks(object):
    _locks_module = django.core.files.locks

    def __init__(self, fs):
        pass

    @staticmethod
    def lock(f, flags):
        return True

    @staticmethod
    def unlock(f):
        return True

    def __getattr__(self, name):
        """Forwards any non-faked calls to the standard module."""
        return getattr(self._locks_module, name)


class FakeFSTestCase(pyfakefs.fake_filesystem_unittest.TestCase):
    def __init__(self, methodName='runTest'):
        pyfakefs.fake_filesystem_unittest.TestCase.__init__(
            self, methodName, modules_to_patch={'locks': DummyLocks})
```
yields 
```
Traceback (most recent call last):
  File "D:\..\tests\testUploadFilesView.py", line 33, in setUp
    self.setUpPyfakefs()
  File "D:\..\lib\site-packages\pyfakefs\fake_filesystem_unittest.py", line 187, in setUpPyfakefs
    modules_to_patch=modules_to_patch)
  File "D:\..\lib\site-packages\pyfakefs\fake_filesystem_unittest.py", line 350, in __init__
    for fct_name in fake_module.dir():
AttributeError: type object 'DummyLocks' has no attribute 'dir'
```

**Comment by mrbean-bremen** [comment]
While this problem has been fixed, the example still does not work.
Reopen.
