### ISSUE TITLE
'getattr' is not defined with PyCharm debug

### ISSUE THREAD

**Issue by dondublon** [jmcgeheeiv/pyfakefs#464]
**Describe the bug**
When I'm going to stop on PyCharm breakpoint, this exception is raised:
Connected to pydev debugger (build 182.4505.26)
Traceback (most recent call last):
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 750, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 254, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.do_wait_suspend
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 778, in do_wait_suspend
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 469, in process_internal_commands
NameError: global name 'getattr' is not defined
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/Perforce/KiteTestsDevelopment/kite/libs/test2/pyfakefstest.py", line 4, in <module>
    patcher.fs.create_dir("D:\somefile")
  File "D:/Perforce/KiteTestsDevelopment/kite/libs/test2/pyfakefstest.py", line 4, in <module>
    patcher.fs.create_dir("D:\somefile")
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 969, in _pydevd_bundle.pydevd_cython_win32_27_64.SafeCallWrapper.__call__
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 515, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 759, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 750, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.trace_dispatch
  File "_pydevd_bundle\pydevd_cython_win32_27_64.pyx", line 254, in _pydevd_bundle.pydevd_cython_win32_27_64.PyDBFrame.do_wait_suspend
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 778, in do_wait_suspend
    self.process_internal_commands()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2.4\helpers\pydev\pydevd.py", line 469, in process_internal_commands
    if getattr(t, 'is_pydev_daemon_thread', False):
NameError: global name 'getattr' is not defined

**How To Reproduce**
Run in PyCharm this code:

from pyfakefs.fake_filesystem_unittest import Patcher

with Patcher() as patcher:
    patcher.fs.create_dir("D:\somefile")  # <- breakpoint here!

**Your enviroment**
Windows-7-6.1.7601-SP1
('Python', '2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]')
('pyfakefs', '3.5.5')

PyCharm 2018.2.4.

**Comment by mrbean-bremen** [comment]
Ok, I cannot reproduce the exact same problem, but a similar one (under Python 2.7 only).
A part of the PyCharm testrunner is obviously not happy with being patched with the fake file system.
Adding the offending module to skip names solves the problem for me:
```python
with Patcher(additional_skip_names=['pydevd']) as patcher:
    patcher.fs.create_dir(r"D:\somefile")
```
I'm not sure if it is a good idea to add this generally to pyfakefs, as this a specific case, but this is actually what the `additional_skip_names` parameter is for. You can use your own derived version of  `Patcher` that always sets that parameter.

**Comment by mrbean-bremen** [comment]
Yes, this is due to the fact that it patches file system calls in all loaded modules, which can be problematic if some the test environment needs to access the real file system after the test setup. A similar problem happens with pytest, therefore the pyfakefs pytest plugin skips some pytest modules.

**Comment by dondublon** [comment]
I guess, if I make this correction, I lose some info or functional. Can you predict, which?

**Comment by mrbean-bremen** [comment]
No, you shouldn't lose anything. This affects only the test runner.

**Comment by dondublon** [comment]
Thank you.

**Comment by mrbean-bremen** [comment]
@dondublon - I found that PyCharm sets a specific enviroment variable for processes started from it, so I will add this fix generically. I hope that works for you...
