### ISSUE TITLE
Pyfakefs 3.6 test failures

### ISSUE THREAD

**Issue by scarabeusiv** [jmcgeheeiv/pyfakefs#495]
When updating pyfakefs from 3.5.8 to 3.6 release on openSUSE 3 of the tests fail:

```
[   16s] ======================================================================
[   16s] FAIL: test_append_mode_tell_linux_windows (pyfakefs.tests.fake_os_test.RealOsModuleTest)
[   16s] ----------------------------------------------------------------------
[   16s] Traceback (most recent call last):
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/fake_os_test.py", line 1224, in test_append_mode_tell_linux_windows
[   16s]     self.check_append_mode_tell_after_truncate(tell_result)
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/fake_os_test.py", line 1216, in check_append_mode_tell_after_truncate
[   16s]     self.assertEqual(tell_result, f1.tell())
[   16s] AssertionError: 5 != 7L
[   16s] 
[   16s] ======================================================================
[   16s] FAIL: test_fdatasync_pass (pyfakefs.tests.fake_os_test.RealOsModuleTest)
[   16s] ----------------------------------------------------------------------
[   16s] Traceback (most recent call last):
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/fake_os_test.py", line 1768, in test_fdatasync_pass
[   16s]     self.os.fdatasync, test_fd + 10)
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/test_utils.py", line 73, in assert_raises_os_error
[   16s]     self.assertEqual(subtype, exc.errno)
[   16s] AssertionError: 9 != 22
[   16s] 
[   16s] ======================================================================
[   16s] FAIL: test_fsync_pass_posix (pyfakefs.tests.fake_os_test.RealOsModuleTest)
[   16s] ----------------------------------------------------------------------
[   16s] Traceback (most recent call last):
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/fake_os_test.py", line 1740, in test_fsync_pass_posix
[   16s]     self.os.fsync, test_fd + 10)
[   16s]   File "/home/abuild/rpmbuild/BUILD/pyfakefs-3.6/pyfakefs/tests/test_utils.py", line 73, in assert_raises_os_error
[   16s]     self.assertEqual(subtype, exc.errno)
[   16s] AssertionError: 9 != 22
[   16s] 
[   16s] ----------------------------------------------------------------------
```

The tests fail the same way both on py2 and py3.

This is bit problematic for us now as we need 3.6 because we prepare update for pyton 3.8 (where the old 3.5.8 does not work).

**Comment by mrbean-bremen** [comment]
These are real OS tests that actually should not run in your case. I seem to have commented out the relevent code and accidentally checked in - sorry for that.
I will correct this tonight and probably make a new dot release.

**Comment by mrbean-bremen** [comment]
Ok, should work in 3.6.1 release.
