### ISSUE TITLE
Scandir does not always support int fd

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#499]
In the Travis tests, some of the MacOS tests fail like this:
```
ERROR: test_index_access_to_stat_times_returns_int (pyfakefs.tests.fake_os_test.RealScandirFdRelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/build/jmcgeheeiv/pyfakefs/pyfakefs/tests/fake_os_test.py", line 4784, in setUp
    self.dir_entries = list(self.do_scandir())
  File "/Users/travis/build/jmcgeheeiv/pyfakefs/pyfakefs/tests/fake_os_test.py", line 5007, in do_scandir
    return self.scandir(self.dir_fd)
TypeError: scandir: illegal type for path parameter
```
This seems to depend on the used scandir version. The tests and the code shall be adapted to emulate the real behavior.

**Comment by mrbean-bremen** [comment]
Seems to happen for Python 3.7 only under MacOS and Linux, but not under Windows.
