### ISSUE TITLE
Question: use cases (beyond which unit test lib I use)

### ISSUE THREAD

**Issue by staticdev** [jmcgeheeiv/pyfakefs#528]
Hi,

@mrbean-bremen answered a question of mine in StackOverflow, and I got interested in this lib. I am a long time python user, but unfortunately I did not give the required attention to the importance of testing. I know basics (difference of fake, stub, mock, what is a unit of code, etc).

I am practicing testing with a new project that uses pytest, and it has [a module](https://github.com/staticdev/irpf-cei/blob/master/src/irpf_cei/cei.py) that reads XLS reports using pandas and make consolidations on numbers. I think it has potential usage to test many/most methods there, but I am not really sure since documentation says: `pyfakefs will not work with Python libraries (other than os and io)`, but I suspect pandas uses `os` and `io` under the hood.

I also would like to know if you recommend any good materials on unit testing with fakes/pyfakefs/pytest specifically.

**Comment by mrbean-bremen** [comment]
Thanks for the interest!

About pandas - to make it a bit clearer, the full quote from the documentation is:

> pyfakefs will not work with Python libraries (other than os and io) that _use C libraries to access the file system_

So, it would be ok if it used `io` or `os` under the hood. Though a quick glance at the pandas source code shows that it has its own internal `io` module written in C, that uses OS-specific functions to access the file system. So, where this is used, we are out of luck with pyfakefs. It is worth a try, but I'm not very optimistic.

As for documentation regarding pyfakefs: I'm afraid all there is is the [usage documentation](http://jmcgeheeiv.github.io/pyfakefs/master/usage.html) and the [generated API docs](http://jmcgeheeiv.github.io/pyfakefs/master/modules.html). Though we are always open to suggestions as to how to improve the documentation (contributions are also welcome, of course).

**Comment by knightjdr** [comment]
I am in the same situation of wanting to mock the filesystem for a module with `pandas.read_csv` and unfortunately this library is not compatible from my attempts. Works great otherwise though.

**Comment by mrbean-bremen** [comment]
@knightjdr - thanks! I understand that you have tried to use pyfakefs with `pandas`, and it does not work (as I had suspected, but nver got around to test). I'll probably add `pandas` to the list of unsupported modules in the documentation.

@staticdev - do you need more information, or can we close this issue?

**Comment by mrbean-bremen** [comment]
@knightjdr , @staticdev: I just had another look at pandas, and at least for `read_csv`
there is a possibility to use it with pyfakefs - just to let you know in case you are interested..  

Pandas internally uses its `TextFileReader` to read from CSV, and this has an argument `engine` which defines which backend is used for file system access. The default is "c", but if you set it to "python", it will use the standard file system access and thus can be used with pyfakefs.

Patching `TextFileReader` accordingly will do the trick:

```python
from unittest import mock

import pandas as pd
from pandas.io.parsers import TextFileReader

class PythonTextFileReader(TextFileReader):
    def __init__(self, *args, **kwargs):
        kwargs['engine'] = 'python'
        super().__init__(*args, **kwargs)

@mock.patch('pandas.io.parsers.TextFileReader', PythonTextFileReader)
def test_load_csv(fs):
    path = '/foo/bar.csv'
    fs.create_file(path, contents='1,2,3,4')
    df = pd.read_csv(path)
    assert (df.columns == ['1', '2', '3', '4']).all()
```

With pytest, this can be done using a separate fixture:
```python

@pytest.fixture
def pd_fs(fs):
    with mock.patch('pandas.io.parsers.TextFileReader', PythonTextFileReader):
        yield fs

def test_load_csv(pd_fs):
    path = '/foo/bar.csv'
    fs.create_file(path, contents='1,2,3,4')
    df = pd.read_csv(path)
    assert (df.columns == ['1', '2', '3', '4']).all()
```
Unfortunately, this does not help for reading excel files - for that it uses the engine from one of several external packages. I will have a look at this later... would be nice to be able to do something here, as `pandas` is used a lot nowadays, and maybe integrate it into pyfakefs.

**Comment by staticdev** [comment]
Nice work @mrbean-bremen.. so pandas is somewhat compatible. I really liked this lib. Congratulations for the effort. I think you can close the issue from my part.

**Comment by mrbean-bremen** [comment]
@knightjdr, @staticdev: for your information, the current master now has integrated patches for reading both csv and Excel files in pandas. It would be nice if you could try it to make sure it works correctly. If nothing comes up, we'll probably do a new release in a few days.

**Comment by knightjdr** [comment]
Tried to read a csv but I'm getting an error. It could be I'm making a noob mistake - I only started in Python a few weeks ago.

1. Install master branch:
```
pip3 install git+https://github.com/jmcgeheeiv/pyfakefs.git@master
```

2. Package to test
```
import pandas as pd

def parse_as_dataframe(file):
  df = pd.read_csv(file, sep='\t', usecols=['a', 'b'])
  return df
```

3. Test
```
import pandas as pd
import pandas.testing as pd_testing
import pyfakefs.fake_filesystem_unittest

from .parse_as_dataframe import parse_as_dataframe

class ParseAsDataframe(pyfakefs.fake_filesystem_unittest.TestCase):
  def assertDataframeEqual(self, a, b, msg):
    try:
      pd_testing.assert_frame_equal(a, b)
    except AssertionError as e:
      raise self.failureException(msg) from e

  def setUp(self):
    self.setUpPyfakefs()
    self.addTypeEqualityFunc(pd.DataFrame, self.assertDataframeEqual)

  def test(self):
    file_content = (
      'a\tb\n',
      '1\t2\n',
      '3\t4\n',
    )
    file_path = '/test/file.txt'
    self.fs.create_file(file_path, contents=file_content)

    expected = pd.DataFrame([
      { 'a': 1, 'b': 2 },
      { 'a': 3, 'b': 4 },
    ])
    self.assertEqual(parse_as_dataframe('test/file.txt'), expected)
```

Traceback
```
Traceback (most recent call last):
  File "/home/james/code/ml/mlbioid/mlbioid/data/read/saint/test_parse_as_dataframe.py", line 33, in test
    self.assertEqual(parse_as_dataframe('test/file.txt'), expected)
  File "/home/james/code/ml/mlbioid/mlbioid/data/read/saint/parse_as_dataframe.py", line 4, in parse_as_dataframe
    df = pd.read_csv(file, sep='\t', usecols=['a', 'b'])
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/patched_packages.py", line 100, in __call__
    return self.fake_parsers.TextFileReader(*args, **kwargs)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/patched_packages.py", line 112, in __init__
    super().__init__(*args, **kwargs)
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1126, in _make_engine
    self._engine = klass(self.f, **self.options)
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2269, in __init__
    memory_map=self.memory_map,
  File "/home/james/.local/lib/python3.6/site-packages/pandas/io/common.py", line 458, in get_handle
    f = open(path_or_buf, mode, errors="replace", newline="")
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 4450, in open
    newline, closefd, opener)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 4935, in __call__
    return self.call(*args, **kwargs)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 5014, in call
    raw_io=self.raw_io)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/fake_filesystem.py", line 4486, in __init__
    newline=newline, errors=errors)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/helpers.py", line 304, in __init__
    self.putvalue(contents)
  File "/home/james/.local/lib/python3.6/site-packages/pyfakefs/helpers.py", line 412, in putvalue
    self._bytestream.write(self.encoded_string(s))
TypeError: a bytes-like object is required, not 'tuple'
```

**Comment by mrbean-bremen** [comment]
@knightjdr - Thanks for testing this! The problem here is this part:
```py
    file_content = (
      'a\tb\n',
      '1\t2\n',
      '3\t4\n',
    )
    file_path = '/test/file.txt'
    self.fs.create_file(file_path, contents=file_content)
```
`contents` must be of `bytes` or `str` type, as it represents the raw file contents.
If you change the line with `create_file` to:
```py
        self.fs.create_file(file_path, contents='\n'.join(file_content))
```
it shall work.

**Comment by knightjdr** [comment]
Yep, sorry. I messed up my multi-line string. It works perfectly after I fixed that.

**Comment by staticdev** [comment]
@mrbean-bremen I will make tests ASAP. Unfortunately, too busy this week. I was added to my backlog =p

**Comment by brendan-simon-indt** [comment]
My `pytest` fails when using `pyfakefs` with pandas 0.23.3 (installed with apt on a Debian 10 Buster box).  I can get it to work with later versions of pandas installed via pip, however my target device is an 32-bit ARM box and the build system doesn't install gcc and other dev tools required to build the `pandas` package (no wheel is available for 32-bit ARM linux).

Is there a way to get the latest `pyfakefs` to work with an older `pandas` 0.23.3 -- specifically the `pandas.read_csv()` function using the `float_precision='round_trip'` argument?

**Comment by mrbean-bremen** [comment]
@brendan-simon-indt - I just installed `pandas 0.23.3` under Python 7 (albeit under Windows) and run a [simple test](https://github.com/pytest-dev/pyfakefs/blob/main/pyfakefs/tests/patched_packages_test.py), which worked. Can you show a failing test? What Python and pytest versions are you running? I don't think that there is a difference between 32 and 64 bit versions (at least I hope so), so maybe I can reproduce it with a 64 bit Python.

**Comment by brendan-simon-indt** [comment]
@mrbean-bremen - here is my pytest simplified test code.  I created a customised pyfakefs fixture to mock the pandas read_csv() call to get the tests to pass.  You can test using `fs` or `my_fs` by uncommenting/commenting the appropriate lines.

```python
import pytest
import pandas as pd
from io import StringIO

#!------------------------------------------------------------------------

orig_pandas_read_csv = pd.read_csv

def mock_pandas_read_csv( *args, **kwargs ):
    kwargs.pop('float_precision', None)
    return orig_pandas_read_csv( *args, **kwargs )

#!------------------------------------------------------------------------

@pytest.fixture
def my_fs(mocker, fs):
    """
    pyfakefs test fixture with mocked pandas.read_csv()
    """
    mocker.patch.object( pd, 'read_csv', new=mock_pandas_read_csv )
    yield fs

#!------------------------------------------------------------------------

class Test_Pandas_Read_CSV :

    @pytest.mark.parametrize(
            'csv_str,kwargs,exp_status',
            [
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        # engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='python',
                    ),
                    # False,                                  #! exp_status
                    True,                                   #! exp_status
                ),
            ]
        )
    def test_pandas_read_csv(
            self,
            # mocker,                                         #! pytest-mock test fixture
            fs,                                             #! pyfakefs test fixture (with mocked pandas functions)
            # my_fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            csv_str     : str,
            kwargs,
            exp_status  : bool,
            ) :

        try :
            df = pd.read_csv( StringIO(csv_str), **kwargs )
            status = True
        except Exception as exc:
            status = False

        assert status == exp_status
```

**Results with customised pyfakefs fixture that mocks the pandas read_csv() call => passes.**

```pytest
======================================================================== test session starts ========================================================================
platform linux -- Python 3.7.3, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/brendansimon/xxx, configfile: pytest.ini
plugins: pyfakefs-5.1.0, cov-4.0.0, mock-3.10.0
collected 3 items                                                                                                                                                   

pandas_read_csv_test.py ...                                                                                                                                   [100%]

========================================================================= warnings summary ==========================================================================
../../../../venv_3/lib/python3.7/site-packages/pandas/core/dtypes/inference.py:6
  /home/brendansimon/xxx/venv_3/lib/python3.7/site-packages/pandas/core/dtypes/inference.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

../../../../venv_3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3
  /home/brendansimon/xxx/venv_3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=================================================================== 3 passed, 2 warnings in 0.29s ===================================================================
```

**Results with standard pyfakefs fixture => errors.**

```pytest
======================================================================== test session starts ========================================================================
platform linux -- Python 3.7.3, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/brendansimon/xxx, configfile: pytest.ini
plugins: pyfakefs-5.1.0, cov-4.0.0, mock-3.10.0
collected 3 items                                                                                                                                                   

pandas_read_csv_test.py FFF                                                                                                                                   [100%]

============================================================================= FAILURES ==============================================================================
______________________________________ Test_Pandas_Read_CSV.test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs0-True] ______________________________________

self = <pandas_read_csv_test.Test_Pandas_Read_CSV object at 0x7f1e9fcbdd68>, fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f1e9ffb1748>
csv_str = '0.00042119645,3.4,8.8244e-5\r\n', kwargs = {'float_precision': 'round_trip'}, exp_status = True

    @pytest.mark.parametrize(
            'csv_str,kwargs,exp_status',
            [
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        # engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='python',
                    ),
                    # False,                                  #! exp_status
                    True,                                   #! exp_status
                ),
            ]
        )
    def test_pandas_read_csv(
            self,
            # mocker,                                         #! pytest-mock test fixture
            fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            # my_fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            csv_str     : str,
            kwargs,
            exp_status  : bool,
            ) :
        """
        Test pandas read_csv().
        """
    
        try :
            df = pd.read_csv( StringIO(csv_str), **kwargs )
            status = True
        except Exception as exc:
            status = False
    
>       assert status == exp_status
E       assert False == True

/home/brendansimon/xxx/root/opt/sbin/pytest/pandas_read_csv_test.py:105: AssertionError
______________________________________ Test_Pandas_Read_CSV.test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs1-True] ______________________________________

self = <pandas_read_csv_test.Test_Pandas_Read_CSV object at 0x7f1e9fcbddd8>, fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f1eaa668e48>
csv_str = '0.00042119645,3.4,8.8244e-5\r\n', kwargs = {'engine': 'c', 'float_precision': 'round_trip'}, exp_status = True

    @pytest.mark.parametrize(
            'csv_str,kwargs,exp_status',
            [
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        # engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='python',
                    ),
                    # False,                                  #! exp_status
                    True,                                   #! exp_status
                ),
            ]
        )
    def test_pandas_read_csv(
            self,
            # mocker,                                         #! pytest-mock test fixture
            fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            # my_fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            csv_str     : str,
            kwargs,
            exp_status  : bool,
            ) :
        """
        Test pandas read_csv().
        """
    
        try :
            df = pd.read_csv( StringIO(csv_str), **kwargs )
            status = True
        except Exception as exc:
            status = False
    
>       assert status == exp_status
E       assert False == True

/home/brendansimon/xxx/root/opt/sbin/pytest/pandas_read_csv_test.py:105: AssertionError
______________________________________ Test_Pandas_Read_CSV.test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs2-True] ______________________________________

self = <pandas_read_csv_test.Test_Pandas_Read_CSV object at 0x7f1e9fcbdf60>, fs = <pyfakefs.fake_filesystem.FakeFilesystem object at 0x7f1e9f346978>
csv_str = '0.00042119645,3.4,8.8244e-5\r\n', kwargs = {'engine': 'python', 'float_precision': 'round_trip'}, exp_status = True

    @pytest.mark.parametrize(
            'csv_str,kwargs,exp_status',
            [
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        # engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='c',
                    ),
                    True,                                   #! exp_status
                ),
                (
                    ('0.00042119645,3.4,8.8244e-5\r\n'),    #! csv_str
                    dict(                                   #! kwargs
                        float_precision='round_trip',
                        engine='python',
                    ),
                    # False,                                  #! exp_status
                    True,                                   #! exp_status
                ),
            ]
        )
    def test_pandas_read_csv(
            self,
            # mocker,                                         #! pytest-mock test fixture
            fs,                                          #! pyfakefs test fixture (standard)
            # my_fs,                                          #! pyfakefs test fixture (with mocked pandas functions)
            csv_str     : str,
            kwargs,
            exp_status  : bool,
            ) :
        """
        Test pandas read_csv().
        """
    
        try :
            df = pd.read_csv( StringIO(csv_str), **kwargs )
            status = True
        except Exception as exc:
            status = False
    
>       assert status == exp_status
E       assert False == True

/home/brendansimon/xxx/root/opt/sbin/pytest/pandas_read_csv_test.py:105: AssertionError
========================================================================= warnings summary ==========================================================================
../../../../venv_3/lib/python3.7/site-packages/pandas/core/dtypes/inference.py:6
  /home/brendansimon/xxx/venv_3/lib/python3.7/site-packages/pandas/core/dtypes/inference.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

../../../../venv_3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3
  /home/brendansimon/xxx/venv_3/lib/python3.7/site-packages/pandas/core/tools/datetimes.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import MutableMapping

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====================================================================== short test summary info ======================================================================
FAILED pandas_read_csv_test.py::Test_Pandas_Read_CSV::test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs0-True] - assert False == True
FAILED pandas_read_csv_test.py::Test_Pandas_Read_CSV::test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs1-True] - assert False == True
FAILED pandas_read_csv_test.py::Test_Pandas_Read_CSV::test_pandas_read_csv[0.00042119645,3.4,8.8244e-5\r\n-kwargs2-True] - assert False == True
=================================================================== 3 failed, 2 warnings in 0.60s ===================================================================
```

**Comment by mrbean-bremen** [comment]
Ok, thanks - I see the problem now. It is shown in the raised exception:
> ValueError: The 'float_precision' option is not supported with the 'python' engine

I'm afraid there is not much I can do here. As you can see, the `float_precision` parameter is not supported in the Python engine, which pyfakefs uses in the patched version to avoid the problem of C functions used for file system access. Short of implementing this yourself (or backporting that part of the Python engine from a later pandas version) there is not much you can do. 
If you really need to use this parameter in the test, you probably have to test in the real filesystem without `pyfakefs` - sorry!
