### ISSUE TITLE
changing cwd causes errors if simulating other os

### ISSUE THREAD

**Issue by giladreti** [jmcgeheeiv/pyfakefs#557]
**Describe the bug**
When changing the current working directory while using the patched filesystem that mocks a **Linux** filesystem, the fake filesystem gets confused when trying to access **Windows** absolute paths, since absolute paths in Windows are not prefixed with a '/' while in Linux they are. The fake filesystem tries to resolve the path as a relative path in the current working directory and fails.

```
Traceback (most recent call last):
  File "C:/Users/gilad/Documents/my_module/bug.py", line 19, in <module>
    bug()
  File "C:/Users/gilad/Documents/my_module/bug.py", line 16, in bug
    open(__file__)
  File "C:\Users\gilad\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfakefs\fake_filesystem.py", line 4449, in open
    return fake_open(file, mode, buffering, encoding, errors,
  File "C:\Users\gilad\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfakefs\fake_filesystem.py", line 4935, in __call__
    return self.call(*args, **kwargs)
  File "C:\Users\gilad\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfakefs\fake_filesystem.py", line 4983, in call
    file_object = self._init_file_object(file_object,
  File "C:\Users\gilad\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfakefs\fake_filesystem.py", line 5037, in _init_file_object
    self.filesystem.raise_os_error(errno.ENOENT, file_path)
  File "C:\Users\gilad\AppData\Local\Programs\Python\Python38\lib\site-packages\pyfakefs\fake_filesystem.py", line 960, in raise_os_error
    raise OSError(errno, message, filename)
FileNotFoundError: [Errno 2] No such file or directory in the fake filesystem: 'C:/Users/gilad/Documents/my_module/bug.py'
```

**How To Reproduce**

My project tree structure:
```
.
├── __pycache__
│   └── test.cpython-38-pytest-6.0.2.pyc
└── bug.py

1 directory, 2 files
```

My test file:

```python
import os
from pathlib import Path

from pyfakefs.fake_filesystem_unittest import Patcher


def bug():
    with Patcher() as patcher:
        filesystem = patcher.fs
        filesystem.is_windows_fs = filesystem.is_macos = False

        filesystem.add_real_file(__file__)

        open(__file__) # works
        os.chdir(Path.home())
        open(__file__) # fails


bug()
```

**Your enviroment**
Please run the following and paste the output.
```bash
python -c "import platform; print(platform.platform())"
python -c "import sys; print('Python', sys.version)"
python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
```
Output:
```
C:\Users\gilad\Documents\my_module>python -c "import platform; print(platform.platform())"
Windows-10-10.0.19041-SP0

C:\Users\gilad\Documents\my_module>python -c "import sys; print('Python', sys.version)"
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]

C:\Users\gilad\Documents\my_module>python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
pyfakefs 4.1.0
```

**Comment by giladreti** [comment]
This issue was opened twice accidentally.
