### ISSUE TITLE
pathlib.Path.readlink not implemented

### ISSUE THREAD

**Issue by satwell** [jmcgeheeiv/pyfakefs#584]
**Describe the bug**
Python 3.9 added a [`readlink()`](https://docs.python.org/3.9/library/pathlib.html#pathlib.Path.readlink) method to `pathlib.Path`.  Trying to use this method with pyfakefs raises an `AttributeError`.

**How To Reproduce**
```python
from pyfakefs import fake_filesystem, fake_pathlib

fake_fs = fake_filesystem.FakeFilesystem()
fake_pathlib = fake_pathlib.FakePathlibModule(fake_fs)
p = fake_pathlib.Path("/foo/bar")
p.readlink()
```
This will raise an exception like this:
```
Traceback (most recent call last):
  File "/tmp/test_readlink.py", line 6, in <module>
    p.readlink()
  File "/usr/lib/python3.9/pathlib.py", line 1281, in readlink
    path = self._accessor.readlink(self)
AttributeError: '_FakeAccessor' object has no attribute 'readlink'
```

**Your environment**
```Linux-5.9.0-4-amd64-x86_64-with-glibc2.31
Python 3.9.1+ (default, Jan 20 2021, 14:49:22) 
[GCC 10.2.1 20210110]
pyfakefs 4.3.3
```

**Comment by mrbean-bremen** [comment]
Thanks - missed that one!

**Comment by mrbean-bremen** [comment]
Should work now in master, please check.

**Comment by satwell** [comment]
readlink works for me in master now, thanks!
