### ISSUE TITLE
pyfakefs not installing from pypi

### ISSUE THREAD

**Issue by petergillardmoss** [jmcgeheeiv/pyfakefs#64]
Hello,

I get the following error when trying to install pyfakefs from pypi:

```
$ pip install pyfakefs
Collecting pyfakefs
  Downloading pyfakefs-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/59/y54yv6md5h36hkw9pc537rf80000gn/T/pip-build-wMslO8/pyfakefs/setup.py", line 37, in <module>
        LONG_DESCRIPTION = open(readme).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/59/y54yv6md5h36hkw9pc537rf80000gn/T/pip-build-wMslO8/pyfakefs/README.md'
```

**Comment by jcwilson** [comment]
See #45

**Comment by jmcgeheeiv** [comment]
Please try pyfakefs 2.7.

**Comment by jmcgeheeiv** [comment]
@jcwilson, @cburroughs, and Cash Costello confirmed that pyfakefs 2.7 on PyPi works.

Thank you for your patience.
